project:
  type: website

website:
  title: "Charlie Do Amaral"
  favicon: "images/profile.jpg"
  google-analytics: "G-WZ5QTBHBQF"
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Blog
        href: blog_blog.qmd
      - text: Servicios
        href: servicios.qmd
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/charlie-arturo-do-amaral-becerra/

format:
  html:
    theme: 
      light: sketchy
      dark: darkly
    css: styles.css

editor: visual



