project:
  type: website

website:
  title: "Charlie Do Amaral"
  favicon: "images/profile.jpg"
  google-analytics: "G-WZ5QTBHBQF"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/charlie-arturo-do-amaral-becerra/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



